-- USERS

CREATE TABLE dbo.USERS (
    USER_ID     INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    FIRSTNAME   NVARCHAR(255)     NOT NULL,
    LASTNAME    NVARCHAR(255)     NOT NULL,
    DATEOFBIRTH NVARCHAR(255)     NOT NULL,
    EMAIL       NVARCHAR(255)     NOT NULL,
    PASS        NVARCHAR(MAX)     NOT NULL,
    STATUS      NVARCHAR(20)      NOT NULL
);

-- PRODUCTS
CREATE TABLE dbo.PRODUCTS (
    PRODUCT_ID        INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    PRODUCT_NAME      NVARCHAR(50)      NULL,
    PRODUCT_CATEGORY  NVARCHAR(50)      NULL,
    PRICE             DECIMAL(10,2)     NULL,
    DESCRIPTION       NVARCHAR(MAX)     NOT NULL
);

-- PRODUCT_IMAGE
CREATE TABLE dbo.PRODUCT_IMAGE (
    IMAGE_ID    INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    IMAGE_NAME  NVARCHAR(50)      NULL,
    FILEPATH    NVARCHAR(MAX)     NULL,
    PRODUCT_ID  INT               NOT NULL,
    CONSTRAINT FK_PRODUCT_IMAGE_PRODUCT FOREIGN KEY (PRODUCT_ID)
        REFERENCES dbo.PRODUCTS(PRODUCT_ID)
);

-- ORDER (quoted because ORDER is reserved)
CREATE TABLE dbo.[ORDER] (
    ORDER_ID      INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    USER_ID       INT               NULL,
    TOTAL_PRICE   DECIMAL(10,2)     NULL,
    ORDER_PLACED  DATE              NULL,
    PAYMENT       DECIMAL(10,2)     NULL,
    DISCOUNT      NVARCHAR(50)      NOT NULL,
    CONSTRAINT FK_ORDER_USER FOREIGN KEY (USER_ID)
        REFERENCES dbo.USERS(USER_ID)
);

-- ORDER_ITEM
CREATE TABLE dbo.ORDER_ITEM (
    ORDER_ITEM_ID  INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    ORDER_ID       INT               NULL,
    PRODUCT_ID     INT               NULL,
    PRODUCT_NAME   NVARCHAR(50)      NULL,
    QUANTITY       INT               NULL,
    PRICE          DECIMAL(10,2)     NOT NULL,
    CONSTRAINT FK_ORDER_ITEM_ORDER FOREIGN KEY (ORDER_ID)
        REFERENCES dbo.[ORDER](ORDER_ID),
    CONSTRAINT FK_ORDER_ITEM_PRODUCT FOREIGN KEY (PRODUCT_ID)
        REFERENCES dbo.PRODUCTS(PRODUCT_ID)
);
